
services:
  idata_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idata-frontend-container
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.idonate.rule=Host(`idonate.kangtido.life`)"
      - "traefik.http.routers.idonate.entrypoints=websecure"
      - "traefik.http.routers.idonate.tls.certresolver=letsencrypt"
      - "traefik.http.services.idonate.loadbalancer.server.port=3000"
    networks:
      - proxy

networks:
  proxy:
    external: true
