services:
  reactjs-srv:
    image: imagename
    container_name: reactjs-container
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reactjs.tls=true"
      - "traefik.http.routers.reactjs.rule=Host(`idonate.kangtido.life`)"
      - "traefik.http.routers.reactjs.entrypoints=web,websecure"
      - "traefik.http.routers.reactjs.tls.certresolver=letsencrypt"
      # - "traefik.http.services.reactjs.loadbalancer.server.port=3000"
    networks:
      - proxy
networks:
  proxy:
    external: true
