services:
  idata_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idata-frontend-container
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`nextjs.kangtido.life`)"
      - "traefik.http.routers.nextjs.entrypoints=websecure"
      - "traefik.http.routers.nextjs.tls.certresolver=letsencrypt"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"
    volumes:
      -/home/kang/action-ruuner-idonate/.env.production:/app/.env.production
    networks:
      - proxy
