version: "3.9"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`nextjs.kangtido.life`)"
      - "traefik.http.routers.nextjs.entrypoints=websecure"
      - "traefik.http.routers.nextjs.tls.certresolver=letsencrypt"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"
    secrets:
      - nextjs_env
    networks:
      - proxy

secrets:
  nextjs_env:
    file: ./secrets/nextjs_env  # Path to your secret file containing environment variables

networks:
  proxy:
    external: true
